num1 = input('enter 1st number:')
num2 = input('enter 2nd number:')
sss = float(num1) + float(num2)
diff = float(num1) - float(num2)
mul = float(num1) * float(num2)
div = float(num1) / float(num2)
print('the sum is {0}'.format(sss))
print('the difference is {0}'.format(diff))
print('the multiplication is {0}'.format(mul))
print('the division of two numbers is{0}'.format(div))